### ISSUE TITLE
Add the functionality to completely hide the header

### ISSUE THREAD

**Issue by cheton** [facebook/fixed-data-table#255]
Is there a simple way to completely hide the header?
Setting `headerHeight: {0}` still leaves 1px for the bottom border, and I need to override default style like so:
```css
.public_fixedDataTable_header {
    border: none;
}
```
