### ISSUE TITLE
Feature request: allow reversing row order in DOM to support overflowing cell contents

### ISSUE THREAD

**Issue by dbkaplun** [facebook/fixed-data-table#346]

**Comment by dbkaplun** [comment]
Solved via CSS: (actually LESS but you get the idea)
```less
.public_fixedDataTable_bodyRow,
.fixedDataTableCellGroupLayout_cellGroup,
.public_fixedDataTableCell_main { &:hover { overflow: visible; } }
.fixedDataTableRowLayout_rowWrapper,
.public_fixedDataTableCell_main { &:hover { z-index: 1 !important; } }
.public_fixedDataTable_bodyRow .public_fixedDataTableCell_cellContent:hover { .state('info'); }
```
Screenshot:
![screenshot](http://imgur.com/D985keT.png)
This is very useful for tables with cells that have too much content and must be cropped. I think this could be very handy to anyone with very long cells so this should be somewhere in the docs.
