### ISSUE TITLE
Doesn't work 'rowClassNameGetter'

### ISSUE THREAD

**Issue by rayozerets** [facebook/fixed-data-table#457]
I try use rowClassNameGetter, but it is not working. What am I doing wrong?
JS: 
```
    _rowClassNameGetter(index) {
        return 'selected-row'; // selected?'selected':''
    }
    <Table
    ...
    rowClassNameGetter={this._rowClassNameGetter}
    ...
>
```
CSS

```
.selected-row {
  background: red;
}
```

**Comment by dhenson02** [comment]
Actually it probably is working but the background isn't going to show up because the cells have a default background set already.  

I had this problem as well so to work around it I override the provided classes with the following:

```css
.public_fixedDataTableCell_main,
.public_fixedDataTableRow_highlighted .public_fixedDataTableCell_main {
    background-color: inherit;
}
```

Try adding `color: lime;` or something to that class and see what happens then.
